
import java.util.Set;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhruvshah619
 */
public class Subject_Info extends javax.swing.JFrame {
    
    /**
     * Creates new form Subject_Info
     * would create a new subject object on creation
     * the options in the dropdown teachers list would be according to the availability of the teacher!
     */
    AddingInfoToBranches aib;
    Branch branch;
    DefaultListModel dm3;
    public Subject_Info(Branch branch,AddingInfoToBranches aib,DefaultListModel dm3) {
        this.aib=aib;
        this.branch=branch;
        this.dm3=dm3;
        Teacher teacherArr[]=Institute.arrayOfTeachersSet();
        initComponents();
        //add all the names of the teachers to the combobox!
        lblBranchAndSubjectName.setText(branch.getBranchName());
        
        for(Teacher teacher:teacherArr){
            if(checkingTeachersAbsence(branch,teacher)){
                cmbBoxTeachers.addItem(teacher.getTeacherName());
            }
            
        }
    }
    private boolean checkingTeachersAbsence(Branch branch,Teacher teacher){
        Set<Subject> setOfSubjects = branch.getSetOfSubjects();
        /*
            *obtained the setofsubjects that are there in the branch
            *checked if any teacher teaches a subject in a particular branch
            *if so then dont show!
        */
        for(Subject subject:setOfSubjects){
            if(subject.getTeacherName().equals(teacher.getTeacherName())){
                return false;
            }
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBranchAndSubjectName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbBoxTeachers = new javax.swing.JComboBox<>();
        SpnLecPerWeek = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        chkLecture = new javax.swing.JCheckBox();
        chkPractical = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSubjectName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBranchAndSubjectName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        lblBranchAndSubjectName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel1.setText("Choose the Teacher:");

        cmbBoxTeachers.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel2.setText("Lectures/Week");

        chkLecture.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        chkLecture.setSelected(true);
        chkLecture.setText("Lecture");
        chkLecture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkLectureItemStateChanged(evt);
            }
        });
        chkLecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLectureActionPerformed(evt);
            }
        });

        chkPractical.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        chkPractical.setText("Practical/Tutorial");
        chkPractical.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPracticalItemStateChanged(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel3.setText("Subject Name:");

        txtSubjectName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBoxTeachers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SpnLecPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnSave)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(26, 26, 26)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkLecture)
                                .addGap(18, 18, 18)
                                .addComponent(chkPractical)))
                        .addGap(71, 71, 71))
                    .addComponent(lblBranchAndSubjectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubjectName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblBranchAndSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBoxTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpnLecPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(chkLecture)
                    .addComponent(chkPractical))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                aib.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //Here add it to the branches set of subjects,also do one thing,that add it to the list
        subject=new Subject(txtSubjectName.getText(),cmbBoxTeachers.getSelectedItem().toString(),Integer.parseInt(SpnLecPerWeek.getValue().toString()),chkLecture.isSelected(),chkPractical.isSelected());
        branch.addSubject(subject);
        dm3.addElement(subject.getSubjectName());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                aib.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkLectureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkLectureItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLectureItemStateChanged

    private void chkPracticalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPracticalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPracticalItemStateChanged

    private void chkLectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLectureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLectureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subject_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subject_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subject_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subject_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    Subject subject;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnLecPerWeek;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkLecture;
    private javax.swing.JCheckBox chkPractical;
    private javax.swing.JComboBox<String> cmbBoxTeachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBranchAndSubjectName;
    private javax.swing.JTextField txtSubjectName;
    // End of variables declaration//GEN-END:variables
}
